services:
  - type: web
    name: pkl13-auction
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: PUBLIC_URL
        value: https://pkl13-auction.onrender.com
